language: "python"
python:
  - "3.6"
cache:
  directories:
    - $HOME/google-cloud-sdk/
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)/functions
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
    - GOOGLE_APPLICATION_CREDENTIALS=$HOME/credentials.json
    - GCLOUD_PROJECT_ID_STAGING=cidc-dfci-staging
    - GCLOUD_PROJECT_ID_PROD=cidc-dfci
  matrix:
    - FUNCTION=ingest_upload TOPIC=uploads TIMEOUT=540 MEMORY=512
    - FUNCTION=send_email TOPIC=emails TIMEOUT=60 MEMORY=256
    - FUNCTION=generate_csvs TOPIC=patient_sample_update TIMEOUT=60 MEMORY=256
    - FUNCTION=store_auth0_logs TOPIC=daily_cron TIMEOUT=60 MEMORY=256
    - FUNCTION=vis_preprocessing TOPIC=artifact_upload TIMEOUT=120 MEMORY=512
before_install:
  # Install and configure the gcloud SDK. Values for these environment
  # variables must be set in the Travis CI console for this to work:
  #   GCLOUD_SERVICE_ACCOUNT_JSON_STAGING
  #     -> base64-encoded service account JSON credentials for the staging project
  #   GCLOUD_SERVICE_ACCOUNT_JSON_PROD
  #     -> base64-encoded service account JSON credentials for the production project
  - if [ ! -d ${HOME}/google-cloud-sdk/bin ]; then
    rm -rf $HOME/google-cloud-sdk;
    curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - if [ "$TRAVIS_BRANCH" = production ]; then
    gcloud config set project $GCLOUD_PROJECT_ID_PROD;
    export GCLOUD_SERVICE_ACCOUNT_JSON="$GCLOUD_SERVICE_ACCOUNT_JSON_PROD";
    else
    gcloud config set project $GCLOUD_PROJECT_ID_STAGING;
    export GCLOUD_SERVICE_ACCOUNT_JSON="$GCLOUD_SERVICE_ACCOUNT_JSON_STAGING";
    fi
  - echo "$GCLOUD_SERVICE_ACCOUNT_JSON" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS
  - gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS
install:
  - pip install -r requirements.dev.txt
before_script:
  - psql -c "create user cidcdev with password '1234'"
  - psql -c "create database cidctest"
  - psql -c "grant all privileges on database cidctest to cidcdev"
script:
  - pytest
  - black --check functions main.py --target-version=py36

deploy:
  - provider: script
    script: bash deploy/pubsub.sh $FUNCTION $TOPIC .env.staging.yaml $TIMEOUT $MEMORY
    on:
      branch: master
  - provider: script
    script: bash deploy/pubsub.sh $FUNCTION $TOPIC .env.prod.yaml $TIMEOUT $MEMORY
    on:
      branch: production
